Added check of .gitignore to azure pipelines yaml.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -106,6 +106,13 @@ jobs:
       cd DevGuideExamples\DCPS\Messenger
       perl integration_run_test.pl -ExeSubDir %SUBDIR_FOR_MESSENGER%
     displayName: Run Examples DCPS Messenger
+  - script: |
+      echo "##vso[task.setvariable variable=files]$(git clean -nd -e ext)"
+      if $(files) != ""
+        echo "##vso[task.logissue type=error]These files should be gitignored:"
+        echo $(files);
+        exit 1;
+    displayName: Check validity of .gitignore
 
 - job: VisualStudio2017
   timeoutInMinutes: 120
